-- Additive test-only schema for doctrine_processing chunk repository.
CREATE TABLE IF NOT EXISTS doctrine_chunks_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES doctrine_documents(id),
    section_path TEXT NOT NULL DEFAULT '',
    article_number TEXT NOT NULL DEFAULT '',
    article_title TEXT NOT NULL DEFAULT '',
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    content TEXT NOT NULL,
    token_count INTEGER NOT NULL DEFAULT 0 CHECK (token_count >= 0),
    scripture_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    topic_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    content_hash TEXT NOT NULL CHECK (content_hash ~ '^[0-9a-fA-F]{64}$'),
    UNIQUE(document_id, chunk_index),
    UNIQUE(document_id, content_hash)
);
CREATE INDEX IF NOT EXISTS idx_doctrine_chunks_document ON doctrine_chunks_v2(document_id, chunk_index);
