-- Test-only PostgreSQL schema for the doctrine ingestion boundary.
-- Do not apply to sermon_db until data parity and rollback are verified.

CREATE TABLE IF NOT EXISTS denominations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name_ko TEXT NOT NULL,
    name_en TEXT NOT NULL DEFAULT '',
    tradition TEXT NOT NULL DEFAULT '',
    country TEXT NOT NULL DEFAULT '',
    official_site TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS doctrine_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denomination_id BIGINT NOT NULL REFERENCES denominations(id),
    title TEXT NOT NULL,
    document_type TEXT NOT NULL DEFAULT '',
    source_url TEXT NOT NULL,
    source_authority TEXT NOT NULL,
    collection_method TEXT NOT NULL DEFAULT '',
    update_schedule TEXT NOT NULL DEFAULT '',
    license_status TEXT NOT NULL DEFAULT 'UNKNOWN',
    requires_review BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    permission_ref TEXT NOT NULL DEFAULT '',
    license_reviewed_by TEXT NOT NULL DEFAULT '',
    license_reviewed_at TIMESTAMPTZ,
    license_review_note TEXT NOT NULL DEFAULT '',
    last_checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT doctrine_sources_license_active CHECK (NOT active OR license_status IN ('VERIFIED', 'PUBLIC_DOMAIN'))
);

CREATE TABLE IF NOT EXISTS doctrine_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES doctrine_sources(id),
    title TEXT NOT NULL,
    adoption_year INTEGER,
    edition TEXT NOT NULL DEFAULT '',
    language TEXT NOT NULL DEFAULT 'ko',
    official_status TEXT NOT NULL DEFAULT 'UNKNOWN',
    published_at TIMESTAMPTZ,
    retrieved_at TIMESTAMPTZ,
    content_hash TEXT NOT NULL,
    object_storage_key TEXT NOT NULL DEFAULT '',
    mime_type TEXT NOT NULL DEFAULT '',
    review_status TEXT NOT NULL DEFAULT 'DISCOVERED',
    supersedes_document_id BIGINT REFERENCES doctrine_documents(id),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    reviewed_by TEXT NOT NULL DEFAULT '',
    reviewed_at TIMESTAMPTZ,
    review_comment TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT doctrine_documents_hash CHECK (content_hash ~ '^[0-9a-fA-F]{64}$'),
    CONSTRAINT doctrine_documents_not_self_superseded CHECK (supersedes_document_id IS NULL OR supersedes_document_id <> id),
    UNIQUE (source_id, content_hash)
);

CREATE TABLE IF NOT EXISTS source_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES doctrine_sources(id),
    document_id BIGINT REFERENCES doctrine_documents(id),
    checked_at TIMESTAMPTZ NOT NULL,
    http_status INTEGER,
    etag TEXT NOT NULL DEFAULT '',
    last_modified TEXT NOT NULL DEFAULT '',
    content_hash TEXT NOT NULL DEFAULT '',
    object_storage_key TEXT NOT NULL DEFAULT '',
    changed BOOLEAN NOT NULL DEFAULT FALSE,
    error_code TEXT NOT NULL DEFAULT '',
    error_summary TEXT NOT NULL DEFAULT '',
    request_url TEXT NOT NULL DEFAULT '',
    final_url TEXT NOT NULL DEFAULT '',
    mime_type TEXT NOT NULL DEFAULT '',
    content_length BIGINT NOT NULL DEFAULT 0,
    sha256_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ingestion_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES doctrine_sources(id),
    document_id BIGINT REFERENCES doctrine_documents(id),
    status TEXT NOT NULL DEFAULT 'DISCOVERED',
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    error_code TEXT NOT NULL DEFAULT '',
    error_summary TEXT NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    retry_of_job_id BIGINT REFERENCES ingestion_jobs(id),
    job_type TEXT NOT NULL DEFAULT 'INGEST',
    idempotency_key TEXT NOT NULL DEFAULT '',
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    next_retry_at TIMESTAMPTZ,
    http_status INTEGER,
    retry_after INTEGER,
    storage_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
    storage_key TEXT NOT NULL DEFAULT '',
    bytes_received BIGINT NOT NULL DEFAULT 0 CHECK (bytes_received >= 0),
    error_category TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_doctrine_sources_denomination ON doctrine_sources(denomination_id);
CREATE INDEX IF NOT EXISTS idx_doctrine_documents_source_review ON doctrine_documents(source_id, review_status, active);
CREATE INDEX IF NOT EXISTS idx_source_snapshots_source_checked ON source_snapshots(source_id, checked_at);
CREATE INDEX IF NOT EXISTS idx_ingestion_jobs_status ON ingestion_jobs(status, source_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ingestion_jobs_active_idempotency
    ON ingestion_jobs(source_id, idempotency_key)
    WHERE idempotency_key <> '' AND status IN ('DISCOVERED','DOWNLOADING','DOWNLOADED','PARSING','PARSED','PROCESSING');
